@port = 3000

POST http://localhost:{{port}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  covid19CountrySummaries {
    countryCode
    totalConfirmed
    totalDeath
  }
}