subgraphs:
  countries:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ../countries/src/schema.graphql
  covid19:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../covid19/src/schema.graphql
  population:
    routing_url: http://localhost:4003/graphql
    schema:
      file: ../population/src/schema.graphql
