site_name: Reside Health
site_dir: dist

theme:
  language: en
  name: material
  palette:
    primary: black

plugins:
  - search

markdown_extensions:
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
